const carouselItems = [
  {
    name: "Modern apartment on the bay",
    propertyType: "apartment",
    imgUrl: "../../../images/home/property-01.jpg",
    bedrooms: 4,
    bathrooms: 2,
    propertyArea: 1200,
    price: "$4,500/mo",
    listingType: "rent",
  },
  {
    name: "Renovated studio",
    propertyType: "studio",
    imgUrl: "../../../images/home/property-02.jpg",
    bedrooms: 4,
    bathrooms: 2,
    propertyArea: 1200,
    price: "$540,000",
    listingType: "sale",
  },
  {
    name: "Penthouse apartment",
    propertyType: "apartment",
    imgUrl: "../../../images/home/property-03.jpg",
    bedrooms: 3,
    bathrooms: 2,
    propertyArea: 2560,
    price: "$876,000",
    listingType: "sale",
  },
  {
    name: "Modern apartment",
    propertyType: "apartment",
    imgUrl: "../../../images/home/property-04.jpg",
    bedrooms: 1,
    bathrooms: 2,
    propertyArea: 1560,
    price: "$97,000",
    listingType: "sale",
  },
  {
    name: "Contemporary apartment",
    propertyType: "apartment",
    imgUrl: "../../../images/home/property-05.jpg",
    bedrooms: 4,
    bathrooms: 2,
    propertyArea: 1200,
    price: "$13,000/mo",
    listingType: "rent",
  },
  {
    name: "Awesome family home",
    propertyType: "studio",
    imgUrl: "../../../images/home/property-06.jpg",
    bedrooms: 4,
    bathrooms: 2,
    propertyArea: 3400,
    price: "$570,000",
    listingType: "sale",
  },
];


export default carouselItems;